# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: test
        id: test
        run: |
          docker manifest inspect debu99/testapp:latexst; ret=$? || true
          if [[ $ret -eq 0 ]]; then
            echo "image_exist=true" >> $GITHUB_OUTPUT
          else
            echo "image_exist=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      image-exist: ${{ steps.test.outputs.image_exist }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: needs.check.outputs.image-exist == 'true'
    needs: check
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world!, found it is true"

 
